config/routes.rb
Toxo::Application.routes.draw do
  resources :textos

  resources :image_homes

  devise_for :users
  resources :promotions

  resources :products

  resources :marks

  resources :product_types

  resources :categories
  
  resources :config_outlets

  root 'home#home'

  match 'administracion' =>'categories#management', :as =>'administracion', :via => :get
  match 'home' => 'home#home', :as =>'inicio', :via =>:get
  match 'contact' => 'home#contact', :as =>'contacto', :via =>:get
  match 'productos' => 'home#products', :as =>'productos', :via =>:get
  match 'who_are' => 'home#who_are', :as =>'who_are', :via =>:get
  match 'outlet' => 'home#outlet', :as =>'outlet', :via =>:get
  match 'outletcambiado' => 'home#outletcambiado', :as =>'outletcambiado', :via =>:get
  match 'our_marks' => 'home#our_marks', :as =>'our_marks', :via =>:get
  match 'all_products' => 'home#all_products', :as =>'all_products', :via =>:get
  match 'all_promotions' => 'home#promotions', :as =>'all_promotions', :via =>:get
  match 'show_promotion' => 'home#show_promotion', :as =>'show_promotion', :via =>:get
  match 'sales' => 'home#sales', :as =>'sales', :via =>:get
  match 'delete_old_promotion' => 'promotions#delete_old_promotion', :as =>'delete_old_promotion', :via =>:get
  match 'delete_new_collection' => 'products#delete_new_collection', :as =>'delete_new_collection', :via =>:get
  match 'image_zoom' => 'home#image_zoom', :as =>'image_zoom', :via =>:get

  match 'politicacookies' => 'home#politica_cookies', :as =>'politica_cookies', :via =>:get

  match 'up' => 'marks#up', :as =>'up_mark', :via =>:get
  match 'down' => 'marks#down', :as =>'down_mark', :via =>:get

  match 'create_sale' => 'product_types#create_sale', :as =>'create_sale', :via =>:get
  match 'delete_sale' => 'product_types#delete_sale', :as =>'delete_sale', :via =>:get

  match '/sitemap' => 'sitemap#sitemap', :as =>'sitemap', :via=>:get
  
  get '/google6c3e7b71e5e6c093', :to => redirect('/google6c3e7b71e5e6c093.html')

end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product_type, only: [:show, :edit, :update, :destroy]

  # GET /product_types
  # GET /product_types.json
  def index
    if params[:category_id].nil?
      @product_types = ProductType.all.order(:name)
    else
      @product_types = Category.find(params[:category_id]).product_type.order(:name)
      @category_id = params[:category_id]
    end
    @categories = Category.all.order(:name)
  end

  # GET /product_types/1
  # GET /product_types/1.json
  def show
    @category_id = params[:category_id]
    @categories_associated = @product_type.category
  end

  # GET /product_types/new
  def new
    @category_id = params[:category_id]
    @product_type = ProductType.new
  end

  # GET /product_types/1/edit
  def edit
    @category_id = params[:category_id]
    @categories_associated = @product_type.category
  end

  # POST /product_types
  # POST /product_types.json
  def create
    @product_type = ProductType.new(product_type_params)

    respond_to do |format|
      if @product_type.save
        if !@categories = params[:product_types].nil?
          @categories = params[:product_types][:categories]
          save_relation_with_categories(@categories, nil)
        end

        @category_id = session[:category_id]
        session[:category_id] = nil
        format.html { redirect_to product_types_path(:category_id => @category_id), notice: 'Product type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_types/1
  # PATCH/PUT /product_types/1.json
  def update
    respond_to do |format|
      if @product_type.update(product_type_params)
        if params[:product_types].nil?
          destroy_relations_with_categories @product_type.id
        else
          
          @categories_saved = CategoryProductType.get_relations @product_type.id
          p @categories_saved
          
          destroy_relations_with_categories @product_type.id
          @categories = params[:product_types][:categories]
          save_relation_with_categories(@categories, @categories_saved)
        end

        @category_id = session[:category_id]
        session[:category_id] = nil
        format.html { redirect_to product_types_path(:category_id => @category_id), notice: 'Product type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1
  # DELETE /product_types/1.json
  def destroy
    destroy_relations_with_categories @product_type.id
    @product_type.destroy

    @category_id = session[:category_id]
    session[:category_id] = nil
    redirect_to product_types_path(:category_id => @category_id)
    
  end

  def create_sale
    @product_type_id = params[:product_type_id]
    @category_id = params[:category_id]
    @relation = CategoryProductType.where('product_type_id = ? and category_id = ?', @product_type_id, @category_id)
    @relation.each do |rel|
      rel.sale = 1
      rel.save
      Product.where('product_type_id = ? and category_id = ?', rel.product_type_id, rel.category_id).update_all(sale: 1)
    end
    redirect_to edit_product_type_path(@product_type_id)
  end

  def delete_sale
    @product_type_id = params[:product_type_id]
    @category_id = params[:category_id]
    @relation = CategoryProductType.where('product_type_id = ? and category_id = ?', @product_type_id, @category_id)
    @relation.each do |rel|
      rel.sale = 0
      rel.save
      Product.where('product_type_id = ? and category_id = ?', rel.product_type_id, rel.category_id).update_all(sale: nil)
    end
    redirect_to edit_product_type_path(@product_type_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_type
      @product_type = ProductType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_type_params
      params.require(:product_type).permit(:name)
    end

    def save_relation_with_categories(categories, categories_old)
      if !categories.nil? && categories.length >0
        categories.each do |cat|
          if cat != ""
            @exists = CategoryProductType.where('category_id = ? and product_type_id = ?', cat, @product_type.id)
            if @exists.nil? || @exists.length == 0
              @new_cpt = CategoryProductType.new
              @new_cpt.category_id = cat
              @new_cpt.product_type_id = @product_type.id
              if !categories_old.nil?
                categories_old.each do |co|
                  if co.category_id == @new_cpt.category_id &&
                      co.product_type_id == @new_cpt.product_type_id
                    @new_cpt.sale = 1
                  end
                end
              end
              @new_cpt.save
            end
          end
        end
      end
    end

    def destroy_relations_with_categories product_type_id
      @relations_to_destroy =  CategoryProductType.where('product_type_id=?', product_type_id)
      @relations_to_destroy.each do |ctp|
        ctp.destroy
      end
    end
end

app/helpers/product_types_helper.rb
module ProductTypesHelper

  def has_relation (category_id, product_type_id)
    @relation = CategoryProductType.where('category_id = ? and product_type_id = ?', category_id, product_type_id)

    if @relation.nil? or @relation.length == 0
      return false
    end
    return true
  end

  def is_for_sale(product_type_id, category_id)
    @cpt = CategoryProductType.where('product_type_id = ? and category_id = ?', product_type_id, category_id)

    if @cpt.length > 0 && @cpt[0].sale==1
      return true
    end
    return false
  end

  def find_product_types_with_products category_id
    ProductType.joins('join products on products.product_type_id = product_types.id').where('products.category_id = ?',category_id.to_i).uniq.order(:name)
  end

end

app/views/product_types/_form.html.haml
.row
  .col-sm-6
    .well.bs-component
      .form-horizontal
        = form_for @product_type do |f|
          -set_params(@category_id, nil, nil)
          - if @product_type.errors.any?
            #error_explanation
              .alert.alert-dismissable.alert-danger
                %h4= "Se ha encontrado #{pluralize(@product_type.errors.count, "error")}"
                = error_messages_for @product_type
          .form-group
            = f.label :name, :class=>'col-sm-2 control-label'
            .col-sm-10
              = f.text_field :name, :class=>'form-control'

          .form-group
            .col-sm-2.control-label
              %b
                = t('product_type.categories_asociated')
            .col-sm-10
              .panel.panel-default
                .panel-body
                  - Category.all.each do |acat|
                    
                    -if !@categories_associated.nil?
                      =check_box_tag "product_types[categories][]", acat.id, @categories_associated.include?(acat)
                    -else
                      =check_box_tag "product_types[categories][]", acat.id, false
                    =acat.name

                    -if !@categories_associated.nil? and @categories_associated.include?(acat)
                      -if is_for_sale(@product_type.id, acat.id)
                        .span.label.label-success Está rebajado
                        =link_to 'Eliminar rebaja', delete_sale_path(:product_type_id=>@product_type.id, :category_id=>acat.id), :class=>'label label-danger'
                      -else
                        =link_to 'Rebajar', create_sale_path(:product_type_id=>@product_type.id, :category_id=>acat.id), :class=>'label label-info'
                    %br
                    %br

          .form-group
            .col-sm-10.col-sm-offset-2
              = f.submit 'Guardar', :class=>'btn btn-primary foo'

  .col-sm-6
    =link_to 'Ver marcas asociadas', marks_path(:category_id => @category_id,:product_type_id => @product_type.id), :class=>'btn btn-success'

app/views/product_types/edit.html.haml
.container
  .bs-docs-section
    .row
      .col-sm-12
        .page-header
          %h3 Modificar tipo de producto

    = render 'form'
    
    = link_to 'Volver atrás', product_types_path(:category_id=>@category_id), :class=>'btn btn-danger'

app/views/product_types/index.html.haml
.container
  .col-sm-12
    .page-header
      %h1 Toxo Piel: Tipos de productos
    .bs-component
      .well
        %p
          .col-sm-10
            = link_to 'Crear tipo de producto', new_product_type_path(:category_id=>@category_id), :class=>'btn btn-primary'
          .col-sm-2
            = link_to 'Volver al índice', administracion_path, :class=>'btn btn-danger'
        %table.table.table-striped.table-hover
          %tr.info
            %th.th
              Nombre
            -@categories.each do |category|
              %th.th
                =category.name
            %th.th
              Acciones
          -@product_types.each do |product_type|
            %tr.warning
              %td.td
                = link_to product_type.name, edit_product_type_path(product_type,:category_id=>@category_id)
              -@categories.each do |category|
                %td.td
                  -if has_relation(category.id, product_type.id)
                    = image_tag 'check.png', :size=>'20x20'
                    
              %td.td
                -set_params(@category_id, nil, nil)
                = link_to (image_tag 'delete.jpg', :size=>'20x20'), product_type, method: :delete, data: { confirm: '¿Está seguro de borrar el tipo de producto?' }

        - if @product_types.empty?
          .alert.alert-dismissable.alert-danger
            %p No se han encontrado tipos de producto

        

app/views/product_types/new.html.haml
.container
  .bs-docs-section
    .row
      .col-sm-12
        .page-header
          %h3 Nuevo tipo de producto

    = render 'form'

    = link_to 'Volver a la lista de tipos de productos', product_types_path(:category_id=>@category_id), :class=>'btn btn-danger'

app/views/product_types/show.html.haml
.container
  .bs-docs-section
    .row
      .col-sm-12
        .page-header
          %h3 Información del tipo de producto

  .col-sm-6
    .well
      .bs-component
        .panel.panel-primary
          .panel-heading
            = t('product_type.data')
          %p
            %b= t('product_type.name')+': '
            = @product_type.name

        .panel.panel-primary
          .panel-heading
            = t('product_type.categories_asociated')

          .panel-body
            -Category.all.each do |cat|
              -@categories_associated.each do |category|
                -if (cat.id == category.id)
                  .col-sm-4
                    .well.well-sm
                      = cat.name

  .col-sm-6
    .well
      .bs-component
        %p
          =link_to 'Modificar datos', edit_product_type_path(@product_type,:category_id=>@category_id), :class=>'btn btn-primary'
        %p
          =link_to 'Ver marcas asociadas', marks_path(:product_type_id => @product_type.id), :class=>'btn btn-success'

  .col-sm-12
    = link_to 'Volver a la lista de tipos de productos', product_types_path(:category_id=>@category_id), :class=>'btn btn-danger'