config/routes.rb
Toxo::Application.routes.draw do
  resources :textos

  resources :image_homes

  devise_for :users
  resources :promotions

  resources :products

  resources :marks

  resources :product_types

  resources :categories
  
  resources :config_outlets

  root 'home#home'

  match 'administracion' =>'categories#management', :as =>'administracion', :via => :get
  match 'home' => 'home#home', :as =>'inicio', :via =>:get
  match 'contact' => 'home#contact', :as =>'contacto', :via =>:get
  match 'productos' => 'home#products', :as =>'productos', :via =>:get
  match 'who_are' => 'home#who_are', :as =>'who_are', :via =>:get
  match 'outlet' => 'home#outlet', :as =>'outlet', :via =>:get
  match 'outletcambiado' => 'home#outletcambiado', :as =>'outletcambiado', :via =>:get
  match 'our_marks' => 'home#our_marks', :as =>'our_marks', :via =>:get
  match 'all_products' => 'home#all_products', :as =>'all_products', :via =>:get
  match 'all_promotions' => 'home#promotions', :as =>'all_promotions', :via =>:get
  match 'show_promotion' => 'home#show_promotion', :as =>'show_promotion', :via =>:get
  match 'sales' => 'home#sales', :as =>'sales', :via =>:get
  match 'delete_old_promotion' => 'promotions#delete_old_promotion', :as =>'delete_old_promotion', :via =>:get
  match 'delete_new_collection' => 'products#delete_new_collection', :as =>'delete_new_collection', :via =>:get
  match 'image_zoom' => 'home#image_zoom', :as =>'image_zoom', :via =>:get

  match 'politicacookies' => 'home#politica_cookies', :as =>'politica_cookies', :via =>:get

  match 'up' => 'marks#up', :as =>'up_mark', :via =>:get
  match 'down' => 'marks#down', :as =>'down_mark', :via =>:get

  match 'create_sale' => 'product_types#create_sale', :as =>'create_sale', :via =>:get
  match 'delete_sale' => 'product_types#delete_sale', :as =>'delete_sale', :via =>:get

  match '/sitemap' => 'sitemap#sitemap', :as =>'sitemap', :via=>:get
  
  get '/google6c3e7b71e5e6c093', :to => redirect('/google6c3e7b71e5e6c093.html')

end

app/models/mark.rb
class Mark < ActiveRecord::Base
  has_attached_file :image, styles: { medium: '200x200>', thumb: '48x48>' }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  validates :name, :presence => true
  has_many :mark_product_types
  has_many :product_type, :through=> :mark_product_types
  has_many :products

end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_mark, only: [:show, :edit, :update, :destroy]

  # GET /marks
  # GET /marks.json
  def index
    if params[:product_type_id].nil?
      @marks = Mark.all.order(:priority)
    else
      @category_id = params[:category_id]
      @product_type_id = params[:product_type_id]
      if !@category_id.nil?
        @marks = Array.new
        Category.find(@category_id).product_type.where('product_types.id = ?',@product_type_id).each do |pt|
          pt.mark.where('category_id = ?', @category_id).order(:priority).each do |m|
            @marks << m
          end
        end
      else
        @marks = ProductType.find(@product_type_id).mark.order(:priority).uniq
      end
    end
  end

  # GET /marks/1
  # GET /marks/1.json
  def show
    @product_type_id = params[:product_type_id]
    @category_id = params[:category_id]
    @product_type_associated = @mark.product_type
  end

  # GET /marks/new
  def new
    @product_type_id = params[:product_type_id]
    @category_id = params[:category_id]
    @mark = Mark.new
  end

  # GET /marks/1/edit
  def edit
    @product_type_id = params[:product_type_id]
    @category_id = params[:category_id]
    @product_type_associated = MarkProductType.where('mark_id = ?', @mark.id)
  end

  # POST /marks
  # POST /marks.json
  def create
    @mark = Mark.new(mark_params)
    
    @mark.priority = Mark.count+1
    respond_to do |format|
      if @mark.save
        if !params[:marks].nil?
          @product_types = params[:marks][:product_types]
          save_relation_with_product_types @product_types
        end

        @category_id = session[:category_id]
        session[:category_id] = nil
        @product_type_id = session[:product_type_id]
        session[:product_type_id] = nil
        format.html { redirect_to marks_path(:category_id => @category_id, :product_type_id => @product_type_id), notice: 'Mark was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mark }
      else
        format.html { render action: 'new' }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marks/1
  # PATCH/PUT /marks/1.json
  def update
    respond_to do |format|
      if @mark.update(mark_params)

        if params[:marks].nil?
          destroy_relations_with_product_types @mark.id
        else
          destroy_relations_with_product_types @mark.id
          @product_types = params[:marks][:product_types]
          save_relation_with_product_types @product_types
        end

        @category_id = session[:category_id]
        session[:category_id] = nil
        @product_type_id = session[:product_type_id]
        session[:product_type_id] = nil
        format.html { redirect_to marks_path(:category_id => @category_id, :product_type_id => @product_type_id), notice: 'Mark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marks/1
  # DELETE /marks/1.json
  def destroy
    destroy_relations_with_product_types @mark.id
    @mark.destroy

    @category_id = session[:category_id]
    session[:category_id] = nil
    @product_type_id = session[:product_type_id]
    session[:product_type_id] = nil
    redirect_to marks_path(:category_id => @category_id, :product_type_id => @product_type_id)
  end

  def up
    @mark = Mark.find(params[:mark_id])
    if @mark.priority > 1
      @previous_mark = Mark.where('priority = ?',@mark.priority-1)
      @previous_mark.each do |pm|
        pm.priority = pm.priority + 1
        pm.save
      end
      @mark.priority = @mark.priority - 1
      @mark.save
    end

    respond_to do |format|
      format.html { redirect_to marks_path }
    end
  end

  def down
    @mark = Mark.find(params[:mark_id])
    if @mark.priority < Mark.count
      @previous_mark = Mark.where('priority = ?',@mark.priority+1)
      @previous_mark.each do |pm|
        pm.priority = pm.priority - 1
        pm.save
      end
      @mark.priority = @mark.priority + 1
      @mark.save
    end

    respond_to do |format|
      format.html { redirect_to marks_path }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mark
      @mark = Mark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mark_params
      params.require(:mark).permit(:name, :url, :image, :hidden)
    end

    def save_relation_with_product_types product_types
      if !product_types.nil? && product_types.length >0
        product_types.each do |pt|
          if pt != ""
            @values = pt.split
            @exists = MarkProductType.where('product_type_id = ? and category_id=? and mark_id = ? ', @values[0], @values[1], @mark.id)
            if @exists.nil? || @exists.length == 0
              @new_cpt = MarkProductType.new
              @new_cpt.product_type_id = @values[0]
              @new_cpt.category_id = @values[1]
              @new_cpt.mark_id = @mark.id
              @new_cpt.save
            end
          end
        end
      end
    end

    def destroy_relations_with_product_types mark_id
      @relations_to_destroy =  MarkProductType.where('mark_id=?', mark_id)
      @relations_to_destroy.each do |ctp|
        ctp.destroy
      end
    end
end

app/helpers/marks_helper.rb
module MarksHelper

  def checked(cat_id, pt_id, product_types_associated)
    product_types_associated.each do |pta|
      if pta.product_type_id == pt_id and pta.category_id == cat_id
        return true
      end
    end
    return false
  end
end

app/views/marks/_form.html.haml
.row
  .col-sm-6
    .well.bs-component
      .form-horizontal
        = form_for @mark do |f|
          -set_params(@category_id, @product_type_id, nil)
          - if @mark.errors.any?
            #error_explanation
              .alert.alert-dismissable.alert-danger
                %h4= "Se ha encontrado #{pluralize(@mark.errors.count, "error")}"
                = error_messages_for @mark
          .form-group
            = f.label :name, :class=>'col-sm-2 control-label'
            .col-sm-10
              = f.text_field :name, :class=>'form-control'

          .form-group
            = f.label :hidden, :class=>'col-sm-2 control-label'
            .col-sm-10
              = f.check_box :hidden

          .form-group
            = f.label :image
            .col-sm-10
              = f.file_field :image
          - if !@mark.image.nil?
            .form-group
              =image_tag @mark.image
          .form-group
            .col-sm-2.control-label
              %b
                = t('mark.product_type_asociated')
            .col-sm-10
              .panel.panel-default
                .panel-body
                  - Category.all.order(:name).each do |cat|
                    .btn-xs.btn-success
                      =cat.name
                    %br
                    - cat.product_type.order(:name).each do |pt|
                      -if !@product_type_associated.nil?
                        =check_box_tag "marks[product_types][]", [pt.id, cat.id], checked(cat.id,pt.id,@product_type_associated)
                      -else
                        =check_box_tag "marks[product_types][]", [pt.id, cat.id], false
                      =pt.name
                      %br
                    %br


          .form-group
            .col-sm-10.col-sm-offset-2
              = f.submit 'Guardar', :class=>'btn btn-primary foo', data: { confirm: "Estás a punto de actualizar una MARCA. ¿Estás seguro de querer hacerlo? Si no queires hacerlo solo tienes que pulsar en CANCELAR y no pasará nada.".html_safe, class:'btn-success' }

  .col-sm-6
    =link_to 'Ver productos asociados', products_path(:category_id => @category_id,:product_type_id => @product_type_id,:mark_id => @mark.id), :class=>'btn btn-success'

app/views/marks/edit.html.haml
.container
  .bs-docs-section
    .row
      .col-sm-12
        .page-header
          %h3 Modificar marca

    = render 'form'

    = link_to 'Volver atrás', marks_path(:product_type_id=>@product_type_id), :class=>'btn btn-danger'

app/views/marks/index.html.haml
.container
  .col-sm-12
    .page-header
      %h1 Toxo Piel: Marcas
    .bs-component
      .well
        %p
          .col-sm-10
            = link_to 'Crear una marca', new_mark_path(:product_type_id=>@product_type_id), :class=>'btn btn-primary'
          .col-sm-2
            = link_to 'Volver al índice', administracion_path, :class=>'btn btn-danger'
        %table.table.table-striped.table-hover
          %tr.info
            %th.th
            %th.th
              Nombre
            %th.th
              Tipos de productos
            %th.th
              Acciones
          -@marks.each do |mark|
            %tr.warning
              %td.td
                = link_to (image_tag 'up.png', :size=>'25x25'), up_mark_path(:mark_id => mark.id)
                = link_to (image_tag 'down.png', :size=>'25x25'), down_mark_path(:mark_id => mark.id)
              %td.td
                = link_to edit_mark_path(mark,:product_type_id=>@product_type_id,:category_id=>@category_id) do
                  = image_tag mark.image.url(:thumb)
                  - if (!mark.hidden.nil? && mark.hidden != 0)
                    = mark.name.concat(' -- OCULTA --')
                  - else
                    = mark.name

              %td.td
                -if !mark.product_type.nil?
                  -mark.product_type.each do |mpt|
                    = mpt.name.concat(' - ')

              %td.td
                -set_params(@category_id, @product_type_id, nil)
                = link_to (image_tag 'delete.jpg', :size=>'20x20'), mark, method: :delete, data: { confirm: '¿Está seguro de borrar la marca?' }

        - if @marks.empty?
          .alert.alert-dismissable.alert-danger
            %p No se han encontrado marcas

app/views/marks/new.html.haml
.container
  .bs-docs-section
    .row
      .col-sm-12
        .page-header
          %h3 Nueva marca

    = render 'form'

    = link_to 'Volver a la lista de marcas', marks_path(:product_type_id=>@product_type_id), :class=>'btn btn-danger'

app/views/marks/show.html.haml
.container
  .bs-docs-section
    .row
      .col-sm-12
        .page-header
          %h3 Información de la marca

  .col-sm-6
    .well
      .bs-component
        .panel.panel-primary
          .panel-heading
            = t('mark.data')
          %p
            %b= t('mark.name')+': '
            = @mark.name
          %p
            = image_tag @mark.image.url(:medium)

        .panel.panel-primary
          .panel-heading
            = t('mark.product_type_asociated')

          .panel-body
            -ProductType.all.each do |cat|
              -@product_type_associated.each do |pt|
                -if (cat.id == pt.id)
                  .col-sm-4
                    .well.well-sm
                      = cat.name

  .col-sm-6
    .well
      .bs-component
        %p
          =link_to 'Modificar datos', edit_mark_path(@mark,:product_type_id=>@product_type_id), :class=>'btn btn-primary'
        %p
          =link_to 'Ver productos asociadas', products_path(:mark_id => @mark.id), :class=>'btn btn-success'

  .col-sm-12
    = link_to 'Volver a la lista de marcas', marks_path(:product_type_id=>@product_type_id), :class=>'btn btn-danger'