config/routes.rb
Toxo::Application.routes.draw do
  resources :textos

  resources :image_homes

  devise_for :users
  resources :promotions

  resources :products

  resources :marks

  resources :product_types

  resources :categories
  
  resources :config_outlets

  root 'home#home'

  match 'administracion' =>'categories#management', :as =>'administracion', :via => :get
  match 'home' => 'home#home', :as =>'inicio', :via =>:get
  match 'contact' => 'home#contact', :as =>'contacto', :via =>:get
  match 'productos' => 'home#products', :as =>'productos', :via =>:get
  match 'who_are' => 'home#who_are', :as =>'who_are', :via =>:get
  match 'outlet' => 'home#outlet', :as =>'outlet', :via =>:get
  match 'outletcambiado' => 'home#outletcambiado', :as =>'outletcambiado', :via =>:get
  match 'our_marks' => 'home#our_marks', :as =>'our_marks', :via =>:get
  match 'all_products' => 'home#all_products', :as =>'all_products', :via =>:get
  match 'all_promotions' => 'home#promotions', :as =>'all_promotions', :via =>:get
  match 'show_promotion' => 'home#show_promotion', :as =>'show_promotion', :via =>:get
  match 'sales' => 'home#sales', :as =>'sales', :via =>:get
  match 'delete_old_promotion' => 'promotions#delete_old_promotion', :as =>'delete_old_promotion', :via =>:get
  match 'delete_new_collection' => 'products#delete_new_collection', :as =>'delete_new_collection', :via =>:get
  match 'image_zoom' => 'home#image_zoom', :as =>'image_zoom', :via =>:get

  match 'politicacookies' => 'home#politica_cookies', :as =>'politica_cookies', :via =>:get

  match 'up' => 'marks#up', :as =>'up_mark', :via =>:get
  match 'down' => 'marks#down', :as =>'down_mark', :via =>:get

  match 'create_sale' => 'product_types#create_sale', :as =>'create_sale', :via =>:get
  match 'delete_sale' => 'product_types#delete_sale', :as =>'delete_sale', :via =>:get

  match '/sitemap' => 'sitemap#sitemap', :as =>'sitemap', :via=>:get
  
  get '/google6c3e7b71e5e6c093', :to => redirect('/google6c3e7b71e5e6c093.html')

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html, :xml, :json
  def home
    @images = ImageHome.all
    @textos = Texto.first
  end

  def who_are

  end

  def our_marks

  end

  def all_products
    
  end

  def promotions
    @promotions = Promotion.is_active
  end

  def show_promotion
    @promo = Promotion.find(params[:id])
    @products = Product.where('(outlet is null or outlet = 0)').is_promotion(@promo.id)

    @promotions = Promotion.is_active.limit(10)
  end
  
  def products

    if !params[:mark_id].nil? and !params[:product_type_id].nil? and !params[:category_id].nil?
      @mark = Mark.find(params[:mark_id])
      @product_type = ProductType.find(params[:product_type_id])
      @category = Category.find(params[:category_id])
      @products = Product.joins(:mark).where('(outlet is null or outlet = 0) and marks.hidden = 0 and mark_id = ? and product_type_id = ? and category_id=?', @mark.id, @product_type.id, @category.id).order('marks.name, products.name')
    end
    
    if !params[:mark_id].nil? and !params[:category_id].nil? and params[:product_type_id].nil?
      @mark = Mark.find(params[:mark_id])
      @category = Category.find(params[:category_id])
      @products = Product.joins(:mark).where('(outlet is null or outlet = 0) and marks.hidden = 0 and mark_id = ? and category_id = ?', @mark.id, @category.id).order('marks.name, products.name')
    end

    if !params[:mark_id].nil? and params[:product_type_id].nil? and params[:category_id].nil?
      @mark = Mark.find(params[:mark_id])
      @products = Product.joins(:mark).where('(outlet is null or outlet = 0) and marks.hidden = 0 and mark_id = ?', @mark.id).order('marks.name, products.name')
    end

    if !params[:mark_id].nil? and !params[:product_type_id].nil? and params[:category_id].nil?
      @mark = Mark.find(params[:mark_id])
      @product_type = ProductType.find(params[:product_type_id])
      @products = Product.joins(:mark).where('(outlet is null or outlet = 0) and marks.hidden = 0 and mark_id = ? and product_type_id = ?', @mark.id, @product_type.id).order('marks.name, products.name')
    end

    if !params[:category_id].nil? and !params[:product_type_id].nil? and params[:mark_id].nil?
      @category = Category.find(params[:category_id])
      @product_type = ProductType.find(params[:product_type_id])
      @products = Product.joins(:mark).where('(outlet is null or outlet = 0) and marks.hidden = 0 and category_id = ? and product_type_id = ?', @category.id, @product_type.id).order('marks.name, products.name')
    end

    if !params[:category_id].nil? and params[:product_type_id].nil? and params[:mark_id].nil?
      @category = Category.find(params[:category_id])
      @products = Product.joins(:mark).where('(outlet is null or outlet = 0) and marks.hidden = 0 and category_id = ?', @category.id).order('marks.name, products.name')
    end
  end

  def outletBack
    @products = Product.get_all_products_outlet
  end

  def sales
    @pt_id = params[:product_type_id]
    @cat_id = params[:category_id] 
    if !@cat_id.nil?
      @products = Product.joins(:mark).where('sale = ? and marks.hidden = 0 and (outlet is null or outlet = 0) and (? is null or product_type_id=?) and category_id = ?  and (new_collection is null or new_collection = 0)', 1, @pt_id, @pt_id, @cat_id).order('marks.name, products.name')
    else
      @products = Product.joins(:mark).where('sale = ? and marks.hidden = 0 and (outlet is null or outlet = 0) and (new_collection is null or new_collection = 0)', 1).limit(15).order('random(),name')
    end
  end

  def image_zoom
    @product = Product.find(params[:product_id])
  end

  def google6c3e7b71e5e6c093
    
  end
  
  def politica_cookies
  
  end
  
  def outlet
    @nameCategoriesOutlet = Category.select('name, 1 as tipo').joins('join config_outlets cf on cf.category_id = categories.id')
    @nameCategoriesOutlet = @nameCategoriesOutlet + (ProductType.select('name, 2 as tipo').joins('join config_outlets cf on cf.product_type_id = product_types.id'))
    
    @typeproduct = params[:type]
    @typeproductname = params[:name_type]

    @products = []
    if @typeproduct.nil?
      @desctypeproduct = 'OUTLET'
    else
      @desctypeproduct = 'OUTLET ' + @typeproductname.upcase
    end
    
    @products = Product.get_all_products_outlet_cambiado(@typeproduct, @typeproductname)
  end

end

app/helpers/home_helper.rb
module HomeHelper

  def find_categories(mark, category, product_type)
    if !mark.nil?
      @mark_id = mark.id
    else
      @mark_id = nil
    end

    if !category.nil?
      @category_id = category.id
    else
      @category_id = nil
    end

    if !product_type.nil?
      @product_type_id = product_type.id
    else
      @product_type_id = nil
    end
    @categories = Category.find_categories(@mark_id, @category_id, @product_type_id)
  end

  def find_product_types(mark, category, product_type)
    if !mark.nil?
      @mark_id = mark.id
    else
      @mark_id = nil
    end

    if !category.nil?
      @category_id = category.id
    else
      @category_id = nil
    end

    if !product_type.nil?
      @product_type_id = product_type.id
    else
      @product_type_id = nil
    end
    ProductType.find_product_types(@mark_id, @category_id, @product_type_id)
  end

  def get_mark_id mark
    if mark.nil?
      return nil
    else
      return mark.id
    end
  end

  def get_mark_name mark
    if mark.nil?
      return ''
    else
      return '_'+mark.name
    end
  end
end

app/views/home/_gallery.html.haml
#container.cf
  #main{:role => "main"}
    %section.slider
      .flexslider
        %ul.slides
          -if !@products.nil?
            -@products.each do |product|
              %li
                =image_tag product.image(:original)
          
                - if product.sale == 1 && product.new_collection != 1
                  .carousel-caption_sale
                    %b Rebajado
                - if show_product_in_promotion product
                  .carousel-caption_sale
                    En promoción
                .carousel-caption
                  %h4
                    %b=product.name
                  %p
                    =simple_format(product.description)

app/views/home/_header_home.haml
.container
  .row
    .col-sm-2
      %h1.font_toxo Toxo
    .col-sm-1.alineacion_facebook
      = link_to image_tag('facebook-logo.jpg', :size=>'20x20'), 'https://www.facebook.com/toxosantiago', :target => '_blank'
          
    .col-sm-9
      .alineacion_menu
        = render 'menu'
      
    

app/views/home/_list_products.html.haml
.panel
  -if !@mark.nil?
    =image_tag @mark.image.url(:original), :alt=>@mark.name, :title=>@mark.name
    %br
    %br

  -find_categories(@mark, @category, @product_type).each do |cat|
    .btn-xs.panel_products_custom
      = link_to cat.name, productos_path(:mark_id=>get_mark_id(@mark), :category_id=>cat.id, :anchor=>cat.name+get_mark_name(@mark)), :class =>' btn btn-info'
      .panel
        -find_product_types(@mark,cat, @product_type).each do |pt|
          = link_to pt.name, productos_path(:mark_id=>get_mark_id(@mark), :product_type_id=>pt.id, :category_id=>cat.id, :anchor=>pt.name+'_'+cat.name+get_mark_name(@mark)), :class=>'btn btn-link'
    %br

app/views/home/_menu.html.haml
.bs-docs-section.clearfix
  .row
    .col-sm-12
      .bs-component
        .navbar.navbar-inverse
          .navbar-collapse.collapse.navbar-inverse-collapse
            %ul.nav.navbar-nav
              %li
                = link_to 'Quienes somos', who_are_path(:anchor=>'toxo_historia')

              %li
                = link_to 'Nuestras marcas', our_marks_path(:anchor=>'toxo_marcas')

              %li
                = link_to 'Productos', all_products_path(:anchor=>'toxo_productos')

              - if !Promotion.is_active.nil? && !Promotion.is_active.empty?
                %li.background_menu_promotion_rebajado
                  = link_to 'Promociones', all_promotions_path(:anchor=>'toxo_promociones')

              - if Product.exists_products_outlet
                %li
                  = link_to 'Outlet', outlet_path(:anchor=>'toxo_outlet')

              %li
                = link_to 'Contacto', contacto_path

              - if CategoryProductType.exists_sales
                %li.background_menu_promotion_rebajado
                  = link_to '¡Rebajas!', sales_path(:anchor=>'rebajas_toxo')
              

app/views/home/_pe.html.haml
.bs-docs-section
  .row
    .col-sm-12
      .well-sm
        %p#pepaxina
          
          =link_to 'Visítanos en Santiago de Compostela y Vigo', contacto_path, :class=>'color_outlet'
          |
          Copyrigth © Toxo

= javascript_include_tag "cookie" 

app/views/home/all_products.html.haml
- content_for :meta_title do 'Toxo | Bolsos y complementos' end
- content_for :meta_description do 'Bolsos, billeteras, cinturones, maletas, paraguas y mucho más. Estos son todos nuestros productos' end

.container
  =render 'header_home'

  
  .well
    -Category.all.order(:name).in_groups_of(3).each do |cat_group|
      .row
        -cat_group.each do |cat|
          -if !cat.nil?
            .col-sm-4
              .panel.panel-success
                .panel-heading
                  %h3.panel-title
                  = link_to cat.name, productos_path(:category_id => cat.id, :anchor=>cat.name)
                .panel-body
                  %ul
                    -find_product_types_with_products(cat.id).each do |pt|
                      %li
                        = link_to pt.name, productos_path(:category_id=>cat.id, :product_type_id=>pt.id, :anchor=>cat.name+'_'+pt.name)


  = render 'pe'

app/views/home/contact.html.haml
- content_for :meta_title do 'Toxo | Contacto' end
- content_for :meta_description do 'Toxo tiene tiendas en Santiago de Compostela y Vigo aquí se muestran nuestros datos para ponerse en contacto con nosotros.' end
.container
  =render 'header_home'
    
  

  .well
    .bs-component
      .row
        .col-sm-6
          .alert.alert-dismissable.alert-success

            =link_to 'https://maps.google.com/maps?q=General+Pardi%C3%B1as,+23+santiago+de+compostela&hl=en&ie=UTF8&ll=42.874347,-8.546235&spn=0.002205,0.004935&sll=42.876341,-8.545647&sspn=0.008822,0.019741&hq=General&hnear=R%C3%BAa+do+Xeneral+Pardi%C3%B1as,+23,+15701+Santiago+de+Compostela,+La+Coru%C3%B1a,+Spain&t=m&fll=42.874203,-8.545877&fspn=0.002205,0.004935&z=18&layer=c&cbll=42.874347,-8.546235&panoid=I_5Asv5inguNe8rOXxoYZA&cbp=12,106.03,,0,-3.52', :target => '_blank' do
              =image_tag 'xeral-contacto.jpg'
            %p
              General Pardiñas, 23 - 15701 Santiago de Compostela
            %p
              Tel.: 981 56 39 88 - Fax: 981 55 72 08
        .col-sm-6
          .alert.alert-dismissable.alert-success
            =link_to 'https://maps.google.com/maps?q=area+central&hl=en&ll=42.883222,-8.529436&spn=0.002205,0.004935&sll=42.874347,-8.546235&sspn=0.002221,0.004935&t=m&z=18&layer=c&cbll=42.883222,-8.529436&panoid=u1AgMVMrVXGm8kXODNd46Q&cbp=12,113.2,,0,-6.65', :target => '_blank' do
              =image_tag 'area-contacto.jpg'
            %p
              Área Central, L-18-G - 15707 Santiago de Compostela
            %p
              Tel.: 981 57 08 56 - Fax: 981 57 08 56
            
      .row
        .col-sm-6
          .alert.alert-dismissable.alert-success
            = link_to 'https://maps.google.com/maps?q=Avenida+Garc%C3%ADa+Barb%C3%B3n,+21,+Vigo,+Spain&hl=en&ie=UTF8&ll=42.237219,-8.718257&spn=0.004742,0.009871&sll=37.0625,-95.677068&sspn=41.411029,80.859375&oq=Garc%C3%ADa+Barb%C3%B3n,+21&hnear=Av+Garc%C3%ADa+Barb%C3%B3n,+21,+36201+Vigo,+Pontevedra,+Spain&t=m&z=17&layer=c&cbll=42.237219,-8.718257&panoid=FPnWKgfQeSC4ls5gefzwVA&cbp=12,42.03,,0,-1.66', :target => '_blank' do
              =image_tag 'vigo-contacto.png'
            %p
              García Barbón, 21 - 36201 Vigo
            %p
              Tel.: 986 22 07 14 - Fax: 986 22 79 23

      .row
        -Product.where('category_id=7 and product_type_id=19').each do |p|
          =image_tag p.image.url(:max)

           
  = render 'pe'

app/views/home/outlet.html.haml
- content_for :meta_title do 'Toxo | Outlet' end
- content_for :meta_description do 'Toxo trabaja una gran variedad de marcas de las que ofrecemos los mejores productos' end
.container
  =render 'header_home'
    
  

  .well
    .bs-component
      .row
        .col-sm-12
          .alert.alert-dismissable.alert-danger
            .row
              .col-sm-10
                %center
                  %h1 
                    = @desctypeproduct
            .row.bs-component
              %ul.nav.nav-tabs
                - @nameCategoriesOutlet.each do |cat|
                  %li.nav-item
                    = link_to cat.name,outlet_path(:type=>cat.tipo, :name_type => cat.name,:anchor=>'toxo_outlet')
                %li.nav-item
                  = link_to 'Otros',outlet_path(:type=>3, :name_type =>'Otros',:anchor=>'toxo_outlet')
                    
            -if !@products.nil?
              -@products.each do |rowproduct|
                .row
                  .col-sm-12
                    .row
                      -rowproduct.each do |product|
                        .col-sm-4
                          -if !product.nil?
                            .alert.alert-dismissable.alert-success
                              %p
                                =link_to (image_tag product.image.url(:medium)),  product.image.url(:original), :'data-lightbox'=>'example-1', :class=>'example-image-link'
                              %h4= product.name
                              %p
                                -if !product.description.nil?
                                  =simple_format(product.description)
                              .row
                                .col-sm-4
                                  %span.old_price_outlet
                                    - if !product.old_price.nil?
                                      = "%.2f" % product.old_price
                                  %span.old_price_outlet €
                                .col-sm-4
                                  %b
                                    %span
                                      - if !product.outlet_price.nil?
                                        = "%.2f" % product.outlet_price
                                    %span €
            
  = render 'pe'

app/views/home/outletcambiado.html.haml
- content_for :meta_title do 'Toxo | Outlet' end
- content_for :meta_description do 'Toxo trabaja una gran variedad de marcas de las que ofrecemos los mejores productos' end
.container
  =render 'header_home'
    
  

  .well
    .bs-component
      .row
        .col-sm-12
          .alert.alert-dismissable.alert-danger
            .row
              .col-sm-10
                %center
                  %h1 
                    = @desctypeproduct
            .row.bs-component
              %ul.nav.nav-tabs
                - @nameCategoriesOutlet.each do |cat|
                  %li.nav-item
                    = link_to cat.name,outletcambiado_path(:type=>cat.tipo, :name_type => cat.name,:anchor=>'toxo_outlet')
                %li.nav-item
                  = link_to 'Otros',outletcambiado_path(:type=>3, :name_type =>'Otros',:anchor=>'toxo_outlet')
                    
            -if !@products.nil?
              -@products.each do |rowproduct|
                .row
                  .col-sm-12
                    .row
                      -rowproduct.each do |product|
                        .col-sm-4
                          -if !product.nil?
                            .alert.alert-dismissable.alert-success
                              %p
                                =link_to (image_tag product.image.url(:medium)),  product.image.url(:original), :'data-lightbox'=>'example-1', :class=>'example-image-link'
                              %h4= product.name
                              %p
                                -if !product.description.nil?
                                  =simple_format(product.description)
                              .row
                                .col-sm-4
                                  %span.old_price_outlet
                                    - if !product.old_price.nil?
                                      = "%.2f" % product.old_price
                                  %span.old_price_outlet €
                                .col-sm-4
                                  %b
                                    %span
                                      - if !product.outlet_price.nil?
                                        = "%.2f" % product.outlet_price
                                    %span €
            
  = render 'pe'

app/views/home/politica_cookies.html.haml
.container
  =render 'header_home'
    


  .well
    %h2 Política de cookies
    %p
      Cookie es un fichero que se descarga en su ordenador al acceder a determinadas páginas web. Las cookies permiten a una página web, entre otras cosas, almacenar y recuperar información sobre los hábitos de navegación de un usuario o de su equipo y, dependiendo de la información que contengan y de la forma en que utilice su equipo, pueden utilizarse para reconocer al usuario. El navegador del usuario memoriza cookies en el disco duro solamente durante la sesión actual ocupando un espacio de memoria mínimo y no perjudicando al ordenador. Las cookies no contienen ninguna clase de información personal específica, y la mayoría de las mismas se borran del disco duro al finalizar la sesión de navegador (las denominadas cookies de sesión).
    %p
      La mayoría de los navegadores aceptan como estándar a las cookies y, con independencia de las mismas, permiten o impiden en los ajustes de seguridad las cookies temporales o memorizadas.
    %p
      Sin su expreso consentimiento –mediante la activación de las cookies en su navegador- no enlazará en las cookies los datos memorizados con sus datos personales proporcionados en el momento del registro o la compra.

    %br
    %h4 ¿Qué tipos de cookies utiliza esta página web?

    %ul
      %li Cookies de personalización: Son aquéllas que permiten al usuario acceder al servicio con algunas características de carácter general predefinidas en función de una serie de criterios en el terminal del usuario como por ejemplo serian el idioma, el tipo de navegador a través del cual accede al servicio, la configuración regional desde donde accede al servicio, etc.
      %li Cookies de análisis: Son aquéllas que bien tratadas por nosotros o por terceros, nos permiten cuantificar el número de usuarios y así realizar la medición y análisis estadístico de la utilización que hacen los usuarios del servicio ofertado. Para ello se analiza su navegación en nuestra página web con el fin de mejorar la oferta de productos o servicios que le ofrecemos.
      %li Cookies publicitarias: Son aquéllas que, bien tratadas por nosotros o por terceros, nos permiten gestionar de la forma más eficaz posible la oferta de los espacios publicitarios que hay en la página web, adecuando el contenido del anuncio al contenido del servicio solicitado o al uso que realice de nuestra página web. Para ello podemos analizar sus hábitos de navegación en Internet y podemos mostrarle publicidad relacionada con su perfil de navegación.
      %li Cookies de publicidad comportamental: Son aquéllas que permiten la gestión, de la forma más eficaz posible, de los espacios publicitarios que, en su caso, el editor haya incluido en una página web, aplicación o plataforma desde la que presta el servicio solicitado. Estas cookies almacenan información del comportamiento de los usuarios obtenida a través de la observación continuada de sus hábitos de navegación, lo que permite desarrollar un perfil específico para mostrar publicidad en función del mismo.

    %p
      Cookies de terceros: La Web de Toxo puede utilizar servicios de terceros que, por cuenta de Toxo, recopilarán información con fines estadísticos, de uso del Site por parte del usuario y para la prestacion de otros servicios relacionados con la actividad del Website y otros servicios de Internet.
    %p
      En particular, este sitio Web utiliza Google Analytics, un servicio analítico de web prestado por Google, Inc. con domicilio en los Estados Unidos con sede central en 1600 Amphitheatre Parkway, Mountain View, California 94043.  Para la prestación de estos servicios, estos utilizan cookies que recopilan la información, incluida la dirección IP del usuario, que será transmitida, tratada y almacenada por Google en los términos fijados en la Web Google.com. Incluyendo la posible transmisión de dicha información a terceros por razones de exigencia legal o cuando dichos terceros procesen la información por cuenta de Google.
    %p
      El Usuario acepta expresamente, por la utilización de este Site, el tratamiento de la información recabada en la forma y con los fines anteriormente mencionados. Y asimismo reconoce conocer la posibilidad de rechazar el tratamiento de tales datos o información rechazando el uso de Cookies mediante la selección de la configuración apropiada a tal fin en su navegador. Si bien esta opción de bloqueo de Cookies en su navegador puede no permitirle el uso pleno de todas las funcionalidades del Website.
    %p
      Puede usted permitir, bloquear o eliminar las cookies instaladas en su equipo mediante la configuración de las opciones del navegador instalado en su ordenador:

    %p
      Chrome 
      %br
      Explorer 
      %br
      Firefox 
      %br
      Safari 
      %br

    %p
      Si tiene dudas sobre esta política de cookies, puede contactar con Toxo en toxopiel@gmail.com 

  = render 'pe'

app/views/home/promotions.html.haml
- content_for :meta_title do 'Toxo | Promociones' end
- content_for :meta_description do 'Toxo te ofrece las mejores promociones para que puedas encontrar lo que quieres al mejor precio' end
.container
  =render 'header_home'
    
  

  .well
    .bs-component
      .row
        .col-sm-12
          - @promotions.in_groups_of(3).each do |group_promo|
            .row
              -group_promo.each do |promo|
                .col-sm-4
                  -if !promo.nil? && promo.style == 1
                    .panel.panel-success
                      .panel-heading
                        %h3.panel-title

                      .panel-body
                        
                        %h3
                          = link_to promo.description, show_promotion_path(:id => promo.id)
                        .row
                          .col-sm-8
                            .backgroun_promotion_common
                              =promo.text
                          .col-sm-2
                            =image_tag 'etiqueta_promo.png'
                        %h5= print_dates promo
                          

                  -elsif !promo.nil? && promo.style == 2
                    .panel.panel-danger
                      .panel-heading
                        %h3.panel-title
                    
                      .panel-body
                        %center
                          .text_promotion
                            = promo.text
                            = image_tag 'porcentage.png'
                        %h3
                          = link_to promo.description, show_promotion_path(:id => promo.id)

                        %h5= print_dates promo

                  -elsif !promo.nil? && promo.style == 3
                    .panel.panel-info
                      .panel-heading
                        
                      .panel-body
                        %center
                          =image_tag 'promociones.png'
                        .backgroun_promotion_common
                          =promo.text
                        .row
                          .col-sm-12
                            %h3
                              =link_to promo.description, show_promotion_path(:id => promo.id)
                        
                        %h5= print_dates promo
  = render 'pe'

app/views/home/sales.html.haml
- content_for :meta_title do 'Toxo | Rebajas' end
- content_for :meta_description do 'Las mejores rebajas de Toxo en bolsos y complementos' end
.container
  =render 'header_home'
    
  

  .well
    .bs-component
      .row
        .col-sm-3
          %h3 Las rebajas de Toxo
          -list_sales.each do |ls|
            .btn-success.btn-sm
              = link_to  ls[0].name, sales_path(:category_id => ls[0].id), :class=>'color_outlet'
            %ul
              -ls[1].each do |p|
                %li
                  = link_to p.name, sales_path(:product_type_id =>p.id, :category_id => ls[0].id)
        .col-sm-9
          = render 'gallery'

  = render 'pe'

app/views/home/show_promotion.html.haml
.container
  =render 'header_home'
    
  

  .well
    .bs-component
      .row
        .col-sm-3
          %h4 Alguna de nuestras promociones:
          - @promotions.each do |promo|
            .row
              .btn-xs.panel_products_custom
                %h4= link_to get_text(promo), show_promotion_path(:id => promo.id), :class => 'color_outlet'
              %br
        .col-sm-9
          Estás viendo la promoción
          %b= @promo.description
          = render 'gallery'

  = render 'pe'

app/views/home/who_are.html.haml
- content_for :meta_title do 'Toxo | Quienes somos' end
- content_for :meta_description do 'Consulta la historia de Toxo que describe como nació nuestro negocio familiar' end
.container
  =render 'header_home'

  
  .well.font_who_are
    %center
      = image_tag 'foto_antigua.jpg', :size =>'600x420'
    %p
      Toxo, historia viva.
    %p
      La familia Tojo, somos la tercera generación de una saga de comerciantes que tienen su origen en Santiago de Compostela.
    %p
      Nuestro primer local comercial, abrió sus puertas en Santiago en el año 1913. Estaba ubicado en la plaza de
      Fonte Sequelo, y fue Julio Tojo Fernández, quien, con su local de zapatos comenzó a escribir la historia de nuestra
      familia y nuestro futuro. Adaptándose a las necesidades de la época, la zapatería fue reconvertida en bazar en la posguerra.

    %p
      En 1971, Manolo Tojo Tie, su hijo, abriría un nuevo comercio en Santiago de Compostela, situado en la calle
      %b General Pardiñas 23,
      dedicado a artículos de viaje y piel. Fue Manolo, quien, haciendo gala a su apellido, decide bautizar la tienda
      con el nombre de
      %b TOXO.

    %p
      En 1993, Manolo y Julio Tojo Romero, sus nietos, ampliamos el negocio familiar con la apertura de
      %b TOXO
      en
      %b Área Central -18-g
      en Santiago. Finalmente, en 1997, emprenderíamos nuestra última aventura inaugurando
      %b TOXO
      en Vigo en la calle
      %b García Barbon, número 21.

    %p
      Con más de 100 años de tradición y tres generaciones de comerciantes,
      %b TOXO
      ya forma parte de la historia viva de
      Santiago de Compostela y Vigo, y no podemos más que mostrar nuestro agradecimiento a todos los que habéis
      contribuido a que esta historia sea posible.
    %p
      Gracias por confiar en nosotros.

  = render 'pe'