config/routes.rb
Toxo::Application.routes.draw do
  resources :textos

  resources :image_homes

  devise_for :users
  resources :promotions

  resources :products

  resources :marks

  resources :product_types

  resources :categories
  
  resources :config_outlets

  root 'home#home'

  match 'administracion' =>'categories#management', :as =>'administracion', :via => :get
  match 'home' => 'home#home', :as =>'inicio', :via =>:get
  match 'contact' => 'home#contact', :as =>'contacto', :via =>:get
  match 'productos' => 'home#products', :as =>'productos', :via =>:get
  match 'who_are' => 'home#who_are', :as =>'who_are', :via =>:get
  match 'outlet' => 'home#outlet', :as =>'outlet', :via =>:get
  match 'outletcambiado' => 'home#outletcambiado', :as =>'outletcambiado', :via =>:get
  match 'our_marks' => 'home#our_marks', :as =>'our_marks', :via =>:get
  match 'all_products' => 'home#all_products', :as =>'all_products', :via =>:get
  match 'all_promotions' => 'home#promotions', :as =>'all_promotions', :via =>:get
  match 'show_promotion' => 'home#show_promotion', :as =>'show_promotion', :via =>:get
  match 'sales' => 'home#sales', :as =>'sales', :via =>:get
  match 'delete_old_promotion' => 'promotions#delete_old_promotion', :as =>'delete_old_promotion', :via =>:get
  match 'delete_new_collection' => 'products#delete_new_collection', :as =>'delete_new_collection', :via =>:get
  match 'image_zoom' => 'home#image_zoom', :as =>'image_zoom', :via =>:get

  match 'politicacookies' => 'home#politica_cookies', :as =>'politica_cookies', :via =>:get

  match 'up' => 'marks#up', :as =>'up_mark', :via =>:get
  match 'down' => 'marks#down', :as =>'down_mark', :via =>:get

  match 'create_sale' => 'product_types#create_sale', :as =>'create_sale', :via =>:get
  match 'delete_sale' => 'product_types#delete_sale', :as =>'delete_sale', :via =>:get

  match '/sitemap' => 'sitemap#sitemap', :as =>'sitemap', :via=>:get
  
  get '/google6c3e7b71e5e6c093', :to => redirect('/google6c3e7b71e5e6c093.html')

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, :presence => true
  has_many :category_product_types
  has_many :product_type, :through=> :category_product_types

  def self.find_categories(mark_id, category_id, product_type_id)
    Category.joins('join mark_product_types mpt on mpt.category_id = categories.id').
      where('(mpt.mark_id = ? or ? is null) and (mpt.category_id = ? or ? is null) and (mpt.product_type_id = ? or ? is null)', mark_id, mark_id, category_id, category_id, product_type_id, product_type_id).uniq.order(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def management

  end
  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.order(:name)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
  
  def config_outlet
    
    @categories = Category.all.order(:name).in_groups_of(3)
    @productTypes = ProductType.all.order(:name).in_groups_of(3)

  end
  
  def new_config_outlet
    
    @category_id = params[:category_id]
    
    if !@category_id.nil? && ConfigOutlet.find(@category_id).nil?
      @ConfigOutlet.new(:category_id => @category_id).save
    end

    redirect_to config_outlet_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
    
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
.row
  .col-sm-6
    .well.bs-component
      .form-horizontal
        = form_for @category do |f|
          - if @category.errors.any?
            #error_explanation
              .alert.alert-dismissable.alert-danger
                %h4= "Se ha encontrado #{pluralize(@category.errors.count, "error")}"
                = error_messages_for @category
          .form-group
            = f.label :name, :class=>'col-sm-2 control-label'
            .col-sm-10
              = f.text_field :name, :class=>'form-control'

          .form-group
            .col-sm-10.col-sm-offset-2
              = f.submit 'Guardar', :class=>'btn btn-primary'

  .col-sm-6
    =link_to 'Ver Tipos de productos asociados', product_types_path(:category_id => @category.id), :class=>'btn btn-success'

app/views/categories/config_outlet.html.haml
.container
  .bs-docs-section
    .row
      .col-sm-12
        = link_to 'Volver al índice', administracion_path, :class=>'btn btn-danger'
    .row
      .col-sm-12
        .card.mb-12
          %h3.card-header Categorías
          
          .card-body
            = collection_select(:category_id, :category_id, Category.all.order(:name), :id, :name, {:prompt => 'Selecciona una categoría'}, {:class => 'custom-select'})
            = link_to 'Añadir', new_config_outlet_path(:category_id => @category_id), :class=>'btn btn-primary btn-sm'
          
          %ul.list-group.list-group-flush
            - @categories.each do |cat|
              - cat.each do |c|
                - if !c.nil?
                  %li.list-group-item
                    = c.name
    
    .row
      .col-sm-12
        .card.mb-12
          %h3.card-header Tipos de productos
          
          .card-body
            = collection_select(:product_type_id, :product_type_id, ProductType.all.order(:name), :id, :name, {:prompt => 'Selecciona un tipo'}, {:class => 'custom-select'})
            = link_to 'Añadir', new_product_path, :class=>'btn btn-primary btn-sm'
            
          %ul.list-group.list-group-flush
            - @productTypes.each do |pt|
              - pt.each do |p|
                - if !p.nil?
                  %li.list-group-item
                    = p.name

    = link_to 'Volver al índice', administracion_path, :class=>'btn btn-danger'

app/views/categories/edit.html.haml
.container
  .bs-docs-section
    .row
      .col-sm-12
        .page-header
          %h3 Modificar categoría

    = render 'form'

    = link_to 'Volver atrás', categories_path, :class=>'btn btn-danger'

app/views/categories/index.html.haml
.container
  .col-sm-12
    .page-header
      %h1 Toxo Piel: Categorías
    .bs-component
      .well
        %p
          .col-sm-10
            = link_to 'Crear categoría', new_category_path, :class=>'btn btn-primary'
          .col-sm-2
            = link_to 'Volver al índice', administracion_path, :class=>'btn btn-danger'
        %table.table.table-striped.table-hover
          %tr.info
            %th.th
              Nombre
            %th.th
              Acciones
          -@categories.each do |category|
            %tr.warning
              %td.td
                = link_to category.name, edit_category_path(category)
              %td.td
                = link_to (image_tag 'delete.jpg', :size=>'20x20'), category, method: :delete, data: { confirm: '¿Está seguro de borrar la categoría?' }

        - if @categories.empty?
          .alert.alert-dismissable.alert-danger
            %p No se han encontrado categorías

        
          

app/views/categories/management.html.haml
.container
  .bs-docs-section
    .row.col-sm-12
      .page-header
        %h1 Toxo Piel
      .bs-component
        .jumbotron
          %h3 Administración
          .row
            .col-sm-6
              .bs-component
                .panel.panel-primary
                  .panel-heading
                    %h3 Categorías
                  =link_to image_tag('icono-categorias.png', :size=>'184x184'), categories_path
            .col-sm-6
              .bs-component
                .panel.panel-primary
                  .panel-heading
                    %h3 Tipos de productos
                  =link_to image_tag('icono-productos.jpg', :size=>'184x184'), product_types_path

          .row
            .col-sm-6
              .bs-component
                .panel.panel-primary
                  .panel-heading
                    %h3 Marcas
                  =link_to image_tag('icono-marcas.png', :size=>'240x184'), marks_path
            .col-sm-6
              .bs-component
                .panel.panel-primary
                  .panel-heading
                    %h3 Productos
                  =link_to image_tag('icono-productos-individuales.jpg', :size=>'244x184'), products_path

          .row
            .col-sm-6
              .bs-component
                .panel.panel-primary
                  .panel-heading
                    %h3 Promociones
                  %center
                    =link_to image_tag('promocions.jpg', :size=>'400x200'), promotions_path
            .col-sm-6
              .bs-component
                .panel.panel-primary
                  .panel-heading
                    %h3 Estadísticas
                  %center
                    =link_to image_tag('estadisticas.jpg', :size=>'300x200'), 'http://www.google.es/intl/es/analytics/', :target=>'_blank'

          .row
            .col-sm-6
              .bs-component
                .panel.panel-primary
                  .panel-heading
                    %h3 Outlet
                  %center
                    =link_to image_tag('Outlet.png', :size=>'400x200'), new_config_outlet_path
  
                    
          .row
            .col-sm-6
              .bs-component
                .panel.panel-danger
                  .panel-heading
                    %h3=link_to 'Fotos de portada', image_homes_path

            .col-sm-6
              .bs-component
                .panel.panel-danger
                  .panel-heading
                    %h3=link_to 'Textos Portada', textos_path

app/views/categories/new.html.haml
.container
  .bs-docs-section
    .row
      .col-sm-12
        .page-header
          %h3 Nueva categoría

    = render 'form'

    = link_to 'Volver a la lista de categorías', categories_path, :class=>'btn btn-danger'

app/views/categories/show.html.haml
.container
  .bs-docs-section
    .row
      .col-sm-12
        .page-header
          %h3 Información de la categoría

  .col-sm-6
    .well
      .bs-component
        .panel.panel-primary
          .panel-heading
            = t('categories.data')
          %p
            %b= t('categories.name')+': '
            = @category.name

  .col-sm-6
    .well
      .bs-component
        %p
          =link_to 'Modificar datos', edit_category_path(@category), :class=>'btn btn-primary'
        %p
          =link_to 'Ver Tipos de productos asociados', product_types_path(:category_id => @category.id), :class=>'btn btn-success'

  .col-sm-12
    = link_to 'Volver a la lista de categorías', categories_path, :class=>'btn btn-danger'